# --- example_config.yaml ---
input-dir: "example" # directory with input files per chromosome, see README
output-dir: "results" # directory where to place output
chromosomes: ~ # a list of chromosomes to use (e.g. "chr1"), if None (~) use all `vcf.gz` in `input-dir`
chunk-size: 1.0e6 # target size in base pairs for each singer run
max-missing: 0.6 # ignore chunks with more than this proportion of missing bases
mutation-rate: 1.0e-8 # per base per generation mutation rate
recombination-rate: 1.0e-8 # per base per generation recombination rate, ignored if hapmap is present
polarised: True # are variants polarised so that the reference state is ancestral
mcmc-samples: 100 # number of MCMC samples (each sample is a tree sequence)
mcmc-thin: 10 # thinning interval between MCMC samples
mcmc-burnin: 0.5 # proportion of initial samples discarded when computing plots of statistics
mcmc-resumes: 1000 # maximum number of times to try to resume MCMC on error at a given iteration
coalrate-epochs: 25 # number of time intervals within which to calculate statistics
stratify-by: "population" # column in metadata to stratify statistics by, or None (TODO: not implemented)
random-seed: 1 # random seed
# Optionally, you can also run Polegon and create a
run-polegon: False # whether to run Polegon
# If `use-polegon` is True, Polegon will be run with the following parameters:
polegon-burnin: 100 # Burn-in iterations for MCMC
polegon-samples: 100 # Number of MCMC samples
polegon-scaling-rep: 3 # Number of re-scaling steps
polegon-thin: 10 # Thinning interval length for MCMC
polegon-max-step: 10 # Max step size in MCMC proposal
# TODO: keep MH samples option
# polegon-write-samples: False # Turn on writing samples, if True, MH samples will also be saved
